const E=[10,25,40,60,80],M=[5,12,20,30,45],H=[1,5,10,17,25],DP=[.2,.3,.4,.55,.7],DR=[.2,.3,.45,.6,.8],DS=[.08,.14,.2,.28,.36],DL=[.15,.3,.45,.65,.85],DA=[.1,.18,.28,.4,.5],JJ=[20,50,80,120,160],RUN=[5,12,20,30,45],LNG=[10,20,35,50,70],SHT=[3,8,15,22,30];
// Exercise rows: [name, type, rank thresholds, equipment]. Type: "r" reps, "w" weight x reps, "m" minutes. Equipment: "h" home, "d" dumbbells, "g" gym, "a" anywhere (shown in every mode).
const G={
Chest:[["Push-Up","r",E,"h"],["Diamond Push-Up","r",M,"h"],["Decline Push-Up","r",M,"h"],["Dumbbell Bench Press","w",DP,"d"],["Dumbbell Fly","w",DS,"d"],["Incline Dumbbell Press","w",DP,"d"],["Bench Press","w",[.5,.75,1,1.5,1.75],"g"],["Machine Chest Press","w",[.5,.8,1.1,1.6,1.9],"g"],["Cable Fly","w",[.2,.3,.45,.65,.8],"g"]],
Back:[["Superman","r",E,"h"],["Reverse Snow Angel","r",E,"h"],["Prone Y Raise","r",E,"h"],["One-Arm Dumbbell Row","w",DR,"d"],["Renegade Row","w",DS,"d"],["Dumbbell Pullover","w",DR,"d"],["Dumbbell Shrug","w",DR,"d"],["Barbell Row","w",[.5,.75,1,1.25,1.5],"g"],["Pull-Up","r",H,"g"],["Lat Pulldown","w",[.5,.75,1,1.25,1.5],"g"],["Deadlift","w",[.75,1.25,1.75,2.25,2.75],"g"]],
Legs:[["Bodyweight Squat","r",E,"h"],["Reverse Lunge","r",E,"h"],["Glute Bridge","r",E,"h"],["Jump Squat","r",M,"h"],["Bodyweight Calf Raise","r",E,"h"],["Goblet Squat","w",DL,"d"],["Walking Lunge","w",DL,"d"],["Dumbbell Romanian Deadlift","w",DL,"d"],["Dumbbell Calf Raise","w",DL,"d"],["Squat","w",[.75,1.25,1.5,2,2.5],"g"],["Leg Press","w",[1.5,2.5,3.5,4.5,5.5],"g"],["Romanian Deadlift","w",[.6,1,1.4,1.8,2.2],"g"],["Calf Raise","w",[.5,1,1.5,2,2.5],"g"]],
Shoulders:[["Pike Push-Up","r",M,"h"],["Shoulder Taps","r",E,"h"],["Decline Pike Push-Up","r",[3,8,15,22,30],"h"],["Dumbbell Shoulder Press","w",DP,"d"],["Lateral Raise","w",DS,"d"],["Front Raise","w",DS,"d"],["Rear Delt Fly","w",DS,"d"],["Overhead Press","w",[.35,.55,.75,1,1.25],"g"],["Face Pull","w",[.2,.3,.45,.6,.8],"g"],["Machine Shoulder Press","w",[.5,.8,1.1,1.5,1.9],"g"]],
Arms:[["Close-Grip Push-Up","r",M,"h"],["Bench Dip","r",E,"h"],["Plank Up-Down","r",E,"h"],["Dumbbell Curl","w",DA,"d"],["Hammer Curl","w",DA,"d"],["Overhead Triceps Extension","w",DA,"d"],["Dumbbell Kickback","w",DS,"d"],["Barbell Curl","w",[.2,.35,.55,.75,.95],"g"],["Triceps Pushdown","w",[.3,.5,.75,1,1.25],"g"],["Skull Crusher","w",[.2,.35,.5,.7,.9],"g"],["Dip","r",[3,8,15,25,35],"g"]],
Core:[["Sit-Up","r",E,"h"],["Leg Raise","r",M,"h"],["Bicycle Crunch","r",E,"h"],["Mountain Climber","r",[20,40,60,90,120],"h"],["Weighted Russian Twist","w",DS,"d"],["Dumbbell Side Bend","w",DS,"d"],["Weighted Sit-Up","w",DS,"d"],["Hanging Leg Raise","r",[3,8,15,25,35],"g"],["Cable Crunch","w",[.3,.5,.75,1,1.25],"g"],["Ab Wheel","r",[3,8,15,25,35],"g"]],
Cardio:[["Jumping Jacks","r",JJ,"h"],["High Knees","r",JJ,"h"],["Butt Kicks","r",JJ,"h"],["Burpee","r",M,"h"],["Skater Jump","r",E,"h"],["Running","m",RUN,"a"],["Walking","m",LNG,"a"],["Jump Rope","m",SHT,"h"],["Shadow Boxing","m",SHT,"h"],["Dumbbell Thruster","w",DS,"d"],["Dumbbell Swing","w",DR,"d"],["Dumbbell Snatch","w",DS,"d"],["Man Maker","w",DS,"d"],["Treadmill Run","m",RUN,"g"],["Incline Treadmill Walk","m",LNG,"g"],["Stationary Bike","m",LNG,"g"],["Elliptical","m",LNG,"g"],["Rowing Machine","m",SHT,"g"],["Stair Climber","m",SHT,"g"],["Box Jump","r",M,"g"]]};
const MODES=[["h","Home","No equipment, bodyweight only."],["d","Dumbbells","Dumbbells only. Log the weight of one dumbbell."],["g","Gym","Full equipment: machines, barbells, cables, and dumbbells."]];
const ex9=(a,t)=>{const A=a.map(v=>v*1.25),o=[];let p=0;
  for(let l=1;l<=29;l++){const j=l>=27?3:Math.max(0,Math.floor((l-3)/6)),lo=A[j],hi=A[j+1];let v=lo*Math.pow(hi/lo,(l-3-6*j)/6);v=t!="w"?Math.max(p+1,Math.round(v)):+v.toFixed(3);o.push(v);p=v}
  return o};
const EX={};Object.entries(G).forEach(([g,l])=>l.forEach(([n,t,th,m])=>EX[n]={g,t,th:ex9(th,t),m}));
const UNIT=t=>t=="m"?"min":"reps";
const RANKS=["Page","Squire","Knight","Baron","Viscount","Duke","King","Emperor","Monarch","Sovereign"],rname=l=>RANKS[Math.floor(l/3)]+" "+["III","II","I"][l%3],COL=["#9aa5b1","#a67c52","#8f9ba8","#d1a21c","#6f9f6a","#3f9aa8","#3f6fd0","#c0564f","#e0368a","#8a4fc4"];
